CREATE TABLE IF NOT EXISTS "slide_revision" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slide_id" uuid NOT NULL REFERENCES "slide"("id") ON DELETE CASCADE,
  "version" integer NOT NULL,
  "xml_content" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by" text,
  "reason" text
);

CREATE UNIQUE INDEX IF NOT EXISTS "slide_revision_slide_version_unique"
ON "slide_revision" ("slide_id", "version");

CREATE INDEX IF NOT EXISTS "idx_slide_revision_slide_version"
ON "slide_revision" ("slide_id", "version");

-- Backfill current slide state as first revision for existing data.
INSERT INTO "slide_revision" ("slide_id", "version", "xml_content", "created_by", "reason")
SELECT s."id", s."version", s."xml_content", 'system', 'backfill'
FROM "slide" s
WHERE NOT EXISTS (
  SELECT 1
  FROM "slide_revision" r
  WHERE r."slide_id" = s."id" AND r."version" = s."version"
);
